version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'testedb'
    ports:
      - '5434:5434'

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
